# fly.toml app configuration file generated for preorder on 2026-02-16T09:19:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'preorder'
primary_region = 'bom'

[build]

[env]
  PORT = '3000'
  SCOPES = 'read_customers,read_orders,write_products'
  SHOPIFY_API_KEY = '078f046c957c2c507c56051c17a6610e'
  SHOPIFY_APP_URL = 'https://preorder.fly.dev'

[deploy]
  release_command = "npx prisma db push"

[processes]
  app = 'npm run start'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
