# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "078f046c957c2c507c56051c17a6610e"
name = "Preorder"
application_url = "https://preorder.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products"

[auth]
redirect_urls = [
  "https://preorder.fly.dev/auth/callback",
  "https://preorder.fly.dev/auth/shopify/callback",
  "https://preorder.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://preorder.fly.dev/api"
subpath = "api"
prefix = "apps"
